samples: samples.tsv
units: units.tsv

trimming:
  # skip trimming: false or true
  skip: false
  # the sequencing adapter
  adapter: ACGGATCGATCGATCGATCGAT

ref:
  # the STAR index
  index: "data/ref/index"
  # gtf file with transcripts
  annotation: "data/ref/annotation.chr21.gtf"

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    treated-vs-untreated:
      - treated
      - untreated


threads:
  star: 16
  deseq2: 8

mem:
  star: 96gb
  deseq2: 32gb

params:
  star: "--outSAMtype BAM"
  cutadapt-se: "--minimum-length 20"
  cutadapt-pe: "--minimum-length 20"

